# Generated by Django 6.0.3 on 2026-06-13 06:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wcr', '0004_workcompletionreport_completion_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(db_index=True)),
                ('department', models.CharField(choices=[('OPERATIONS', 'Operations'), ('PROJECTS', 'Projects'), ('ACCOUNTS', 'Accounts'), ('ADMINISTRATION', 'Administration'), ('FIELD', 'Field Operations')], db_index=True, max_length=20)),
                ('activity_type', models.CharField(choices=[('ENQUIRY_PROCESSED', 'Enquiry Processed'), ('SURVEY_SCHEDULED', 'Survey Scheduled'), ('SCHEDULE_CREATED', 'Schedule Created'), ('WCR_VERIFIED', 'WCR Verified'), ('CLIENT_FOLLOWUP', 'Client Follow-up'), ('ESTIMATE_BOQ_PREPARED', 'Estimate BOQ Prepared'), ('QUOTATION_CREATED', 'Quotation Created'), ('EXECUTION_BOQ_PREPARED', 'Execution BOQ Prepared'), ('ORDER_PROCESSED', 'Order Processed'), ('INVOICE_CREATED', 'Invoice Created'), ('INVOICE_VERIFIED', 'Invoice Submitted for Approval'), ('INVOICE_APPROVED', 'Invoice Approved'), ('PAYMENT_FOLLOWUP', 'Payment Follow-up'), ('PAYMENT_RECEIVED', 'Payment Received'), ('USER_APPROVAL', 'User Approval'), ('ATTENDANCE_REVIEW', 'Attendance Review'), ('REPORT_GENERATED', 'Report Generated'), ('WCR_SUBMITTED', 'WCR Submitted'), ('JOB_ATTENDED', 'Job Attended')], db_index=True, max_length=30)),
                ('related_document', models.CharField(blank=True, max_length=120)),
                ('related_model', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='COMPLETED', max_length=15)),
                ('kpi_weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Reserved for future KPI/incentive weighting', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productivity_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'activity_date'], name='productivit_employe_04e9be_idx'), models.Index(fields=['department', 'activity_type'], name='productivit_departm_e995ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProductivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(db_index=True)),
                ('period_month', models.PositiveSmallIntegerField(db_index=True)),
                ('jobs_assigned', models.PositiveIntegerField(default=0)),
                ('jobs_attended', models.PositiveIntegerField(default=0)),
                ('wcr_submitted', models.PositiveIntegerField(default=0)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('man_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
                ('pending_jobs', models.PositiveIntegerField(default=0)),
                ('activities_count', models.PositiveIntegerField(default=0)),
                ('attendance_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completion_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('incentive_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ranking_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('employee', 'period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='WCRTeamParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_role', models.CharField(choices=[('PROJECT_MANAGER', 'Project Manager'), ('SUPERVISOR', 'Supervisor'), ('LEAD_ENGINEER', 'Lead Engineer'), ('SUPPORTING_ENGINEER', 'Supporting Engineer'), ('TECHNICIAN', 'Technician')], max_length=25)),
                ('attended', models.BooleanField(default=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('man_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('from_schedule', models.BooleanField(default=True, help_text='True if auto-loaded from schedule assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wcr_participations', to=settings.AUTH_USER_MODEL)),
                ('wcr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_participants', to='wcr.workcompletionreport')),
            ],
            options={
                'ordering': ['participant_role', 'employee_id'],
                'unique_together': {('wcr', 'employee')},
            },
        ),
    ]
