# Generated by Django 6.0.3 on 2026-06-13 07:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
        ('orders', '0003_order_expected_completion_date_order_order_date_and_more'),
        ('productivity', '0001_initial'),
        ('scheduling', '0003_workschedule_expected_duration_hours_and_more'),
        ('wcr', '0004_workcompletionreport_completion_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSLocationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('address', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('action_type', models.CharField(db_index=True, max_length=30)),
                ('mobile_sync_id', models.CharField(blank=True, help_text='Future Android app sync ID', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_captures', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_records', to='enquiries.enquiry')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_records', to='orders.order')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_records', to='scheduling.workschedule')),
                ('wcr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_records', to='wcr.workcompletionreport')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=25)),
                ('action_type', models.CharField(db_index=True, max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('address', models.TextField(blank=True)),
                ('activity_date', models.DateField(db_index=True)),
                ('activity_time', models.TimeField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('site_photo', models.ImageField(blank=True, upload_to='field/site_photos/')),
                ('work_photo', models.ImageField(blank=True, upload_to='field/work_photos/')),
                ('kpi_weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('mobile_sync_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_activities', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_activities', to='enquiries.enquiry')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_activities', to='orders.order')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_activities', to='scheduling.workschedule')),
                ('wcr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_activities', to='wcr.workcompletionreport')),
                ('gps_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='productivity.gpslocationrecord')),
            ],
            options={
                'ordering': ['-activity_date', '-activity_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSiteAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('check_in_address', models.TextField(blank=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('check_out_address', models.TextField(blank=True)),
                ('site_photo', models.ImageField(blank=True, upload_to='field/checkin_photos/')),
                ('work_photo', models.ImageField(blank=True, upload_to='field/checkout_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_site_attendance', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_attendance', to='scheduling.workschedule')),
            ],
            options={
                'ordering': ['-check_in_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProductivityDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(db_index=True)),
                ('jobs_assigned', models.PositiveIntegerField(default=0)),
                ('jobs_attended', models.PositiveIntegerField(default=0)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('man_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
                ('site_check_ins', models.PositiveIntegerField(default=0)),
                ('completion_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('incentive_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_productivity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_date'],
                'unique_together': {('employee', 'period_date')},
            },
        ),
        migrations.AddIndex(
            model_name='gpslocationrecord',
            index=models.Index(fields=['employee', 'captured_at'], name='productivit_employe_69890d_idx'),
        ),
        migrations.AddIndex(
            model_name='gpslocationrecord',
            index=models.Index(fields=['action_type', 'captured_at'], name='productivit_action__f4be32_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldactivitylog',
            index=models.Index(fields=['employee', 'activity_date'], name='productivit_employe_026965_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldactivitylog',
            index=models.Index(fields=['action_type', 'activity_date'], name='productivit_action__e5a4db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schedulesiteattendance',
            unique_together={('schedule', 'employee')},
        ),
    ]
