"""Enterprise user-management constants — Phase 1 foundation."""

# Default departments (seeded on migration)
DEFAULT_DEPARTMENTS = (
    ('MANAGEMENT', 'Management'),
    ('PROJECTS', 'Projects'),
    ('OPERATIONS', 'Operations'),
    ('ACCOUNTS', 'Accounts'),
    ('PURCHASE', 'Purchase'),
    ('STORES', 'Stores'),
    ('HR_ADMIN', 'HR & Administration'),
    ('CUSTOMER_SUPPORT', 'Customer Support'),
)

# Default designations (seeded on migration)
DEFAULT_DESIGNATIONS = (
    ('DIRECTOR', 'Director'),
    ('PROJECT_MANAGER', 'Project Manager'),
    ('OPERATIONS_MANAGER', 'Operations Manager'),
    ('ACCOUNTS_MANAGER', 'Accounts Manager'),
    ('TEAM_LEADER', 'Team Leader'),
    ('ENGINEER', 'Engineer'),
    ('TECHNICIAN', 'Technician'),
    ('ACCOUNTS_EXECUTIVE', 'Accounts Executive'),
    ('BILLING_EXECUTIVE', 'Billing Executive'),
    ('STORE_EXECUTIVE', 'Store Executive'),
    ('PURCHASE_EXECUTIVE', 'Purchase Executive'),
    ('HR_ADMIN_EXECUTIVE', 'HR & Admin Executive'),
    ('CUSTOMER_SUPPORT_EXECUTIVE', 'Customer Support Executive'),
)

# Permission master catalogue (individual grants per employee)
MODULE_PERMISSIONS = (
    ('dashboard', 'Dashboard', 'operations'),
    ('clients', 'Clients', 'operations'),
    ('orders', 'Orders', 'operations'),
    ('scheduling', 'Scheduling', 'operations'),
    ('special_projects', 'Special Projects', 'operations'),
    ('fleet', 'Fleet & Fuel', 'operations'),
    ('project_expenses', 'Project Expenses', 'finance'),
    ('preventive_maintenance', 'Preventive Maintenance', 'operations'),
    ('boq', 'BOQ', 'operations'),
    ('wcr', 'WCR', 'operations'),
    ('quotation', 'Quotation', 'finance'),
    ('billing', 'Billing', 'finance'),
    ('accounts', 'Accounts', 'finance'),
    ('payments', 'Payments', 'finance'),
    ('purchase', 'Purchase', 'procurement'),
    ('inventory', 'Inventory', 'procurement'),
    ('attendance', 'Attendance', 'hr'),
    ('daily_meeting', 'Daily Meeting', 'operations'),
    ('hr', 'HR', 'hr'),
    ('reports', 'Reports', 'management'),
    ('gps_tracking', 'GPS Tracking', 'operations'),
    ('approval', 'Approval', 'hr'),
    ('cost_analysis', 'Cost Analysis', 'finance'),
    ('vendor_management', 'Vendor Management', 'procurement'),
    ('masters', 'Masters', 'administration'),
    ('user_management', 'User Management', 'administration'),
    ('role_management', 'Role Management', 'administration'),
    ('settings', 'Settings', 'administration'),
    ('system_configuration', 'System Configuration', 'administration'),
    ('database_configuration', 'Database Configuration', 'administration'),
)

# Superuser-only permission codenames (founder / system owner)
SUPERUSER_ONLY_PERMISSIONS = frozenset({
    'user_management',
    'role_management',
    'settings',
    'system_configuration',
    'database_configuration',
})

# Map legacy User.role → default department / designation codes
LEGACY_ROLE_ORG_MAP = {
    'DIRECTOR': ('MANAGEMENT', 'DIRECTOR'),
    'OPERATIONS': ('OPERATIONS', 'OPERATIONS_MANAGER'),
    'PROJECT_MANAGER': ('PROJECTS', 'PROJECT_MANAGER'),
    'SUPERVISOR': ('OPERATIONS', 'TEAM_LEADER'),
    'Supervisor': ('OPERATIONS', 'TEAM_LEADER'),
    'ACCOUNTS': ('ACCOUNTS', 'ACCOUNTS_MANAGER'),
    'ACCOUNTS_EXECUTIVE': ('ACCOUNTS', 'ACCOUNTS_EXECUTIVE'),
    'BACK_OFFICE': ('HR_ADMIN', 'HR_ADMIN_EXECUTIVE'),
    'ENGINEER': ('OPERATIONS', 'ENGINEER'),
    'Technician': ('OPERATIONS', 'TECHNICIAN'),
}

# Map legacy permission module keys (accounts.permissions) → new ModulePermission codename
LEGACY_MODULE_TO_PERMISSION = {
    'dashboard_director': 'dashboard',
    'dashboard_operations': 'dashboard',
    'dashboard_accounts': 'dashboard',
    'dashboard_engineer': 'dashboard',
    'dashboard_supervisor': 'dashboard',
    'dashboard_project_manager': 'dashboard',
    'clients': 'clients',
    'orders': 'orders',
    'orders_create': 'orders',
    'scheduling': 'scheduling',
    'scheduling_manage': 'scheduling',
    'scheduling_field_update': 'scheduling',
    'special_projects': 'special_projects',
    'fleet': 'fleet',
    'project_expenses': 'project_expenses',
    'project_expenses_approve': 'project_expenses',
    'project_expenses_manage': 'project_expenses',
    'preventive_maintenance': 'preventive_maintenance',
    'preventive_maintenance_approve': 'preventive_maintenance',
    'boq': 'boq',
    'estimate_boq': 'boq',
    'wcr': 'wcr',
    'wcr_approve': 'wcr',
    'manage_billing': 'billing',
    'billing': 'billing',
    'quotations': 'quotation',
    'quotation_rates': 'quotation',
    'financial': 'accounts',
    'attendance_manage': 'attendance',
    'attendance_self': 'attendance',
    'attendance_team': 'attendance',
    'attendance_supervisor_team': 'attendance',
    'view_attendance_audit_data': 'attendance',
    'daily_meetings': 'daily_meeting',
    'daily_meetings_manage': 'daily_meeting',
    'case_intelligence': 'reports',
    'productivity': 'reports',
    'erms': 'hr',
    'erms_approve': 'approval',
    'erms_view_all': 'hr',
    'erms_financial_approve': 'approval',
    'user_approval': 'approval',
    'company_settings': 'settings',
    'document_generator': 'masters',
    'user_management': 'user_management',
    'site_progress': 'orders',
    'enquiries': 'clients',
    'enquiries_manage': 'clients',
    'gps_tracking': 'gps_tracking',
}

# Map designation code → legacy role for default permission grants on approval
DESIGNATION_TO_LEGACY_ROLE = {
    'DIRECTOR': 'DIRECTOR',
    'PROJECT_MANAGER': 'PROJECT_MANAGER',
    'OPERATIONS_MANAGER': 'OPERATIONS',
    'ACCOUNTS_MANAGER': 'ACCOUNTS',
    'TEAM_LEADER': 'SUPERVISOR',
    'ENGINEER': 'ENGINEER',
    'TECHNICIAN': 'TECHNICIAN',
    'ACCOUNTS_EXECUTIVE': 'ACCOUNTS_EXECUTIVE',
    'BILLING_EXECUTIVE': 'ACCOUNTS_EXECUTIVE',
    'STORE_EXECUTIVE': 'BACK_OFFICE',
    'PURCHASE_EXECUTIVE': 'BACK_OFFICE',
    'HR_ADMIN_EXECUTIVE': 'BACK_OFFICE',
    'CUSTOMER_SUPPORT_EXECUTIVE': 'BACK_OFFICE',
}
