# Generated by Django 6.0.3 on 2026-06-13 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_migrate_order_scheduling_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='expected_duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Expected Duration (Hours)'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='expected_man_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Expected Man-Days (Team Total)'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='lead_engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ENGINEER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_as_lead_engineer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='project_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PROJECT_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_as_pm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Scheduled Time'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['SUPERVISOR', 'Supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_as_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='supporting_engineers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'ENGINEER'}, related_name='schedules_as_supporting_engineer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='technicians',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'Technician'}, related_name='schedules_as_technician', to=settings.AUTH_USER_MODEL),
        ),
    ]
