# Generated by Django 6.0.3 on 2026-06-13 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
        ('orders', '0003_order_expected_completion_date_order_order_date_and_more'),
        ('scheduling', '0003_workschedule_expected_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='enquiry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_schedule', to='enquiries.enquiry'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('ENQUIRY', 'Enquiry'), ('ORDER', 'Order')], db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='schedule_category',
            field=models.CharField(choices=[('SURVEY', 'Survey'), ('FEASIBILITY', 'Feasibility'), ('INSTALLATION', 'Installation'), ('MAINTENANCE', 'Maintenance'), ('AMC', 'AMC'), ('COMPLAINT', 'Complaint'), ('PROJECT', 'Project')], db_index=True, default='INSTALLATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to='orders.order'),
        ),
    ]
