# Generated by Django 6.0.3 on 2026-06-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_workschedule_enquiry_workschedule_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='field_work_remarks',
            field=models.TextField(blank=True, help_text='Field team work notes and completion remarks.'),
        ),
    ]
