# Generated by Django 6.0.3 on 2026-07-12 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_field_ops_rbac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='lead_engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ENGINEER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_as_lead_engineer', to=settings.AUTH_USER_MODEL, verbose_name='Engineer'),
        ),
    ]
