# Generated by Django 6.1.2 on 2026-10-07 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_workschedule_lead_engineer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='lead_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_as_lead_engineer', to=settings.AUTH_USER_MODEL, verbose_name='Engineer'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_as_pm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_as_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='supporting_engineers',
            field=models.ManyToManyField(blank=True, related_name='schedules_as_supporting_engineer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='schedules_as_technician', to=settings.AUTH_USER_MODEL),
        ),
    ]
