"""Unified schedule categories and reference types."""

REF_ENQUIRY = 'ENQUIRY'
REF_ORDER = 'ORDER'

REFERENCE_TYPE_CHOICES = (
    (REF_ENQUIRY, 'Enquiry'),
    (REF_ORDER, 'Order'),
)

CAT_SURVEY = 'SURVEY'
CAT_FEASIBILITY = 'FEASIBILITY'
CAT_INSTALLATION = 'INSTALLATION'
CAT_MAINTENANCE = 'MAINTENANCE'
CAT_AMC = 'AMC'
CAT_COMPLAINT = 'COMPLAINT'
CAT_PROJECT = 'PROJECT'

SCHEDULE_CATEGORY_CHOICES = (
    (CAT_SURVEY, 'Survey'),
    (CAT_FEASIBILITY, 'Feasibility'),
    (CAT_INSTALLATION, 'Installation'),
    (CAT_MAINTENANCE, 'Maintenance'),
    (CAT_AMC, 'AMC'),
    (CAT_COMPLAINT, 'Complaint'),
    (CAT_PROJECT, 'Project'),
)

ORDER_TYPE_TO_CATEGORY = {
    'SURVEY': CAT_SURVEY,
    'INSTALLATION': CAT_INSTALLATION,
    'COMPLAINT': CAT_COMPLAINT,
    'MAINTENANCE': CAT_MAINTENANCE,
}

ENQUIRY_TYPE_TO_CATEGORY = {
    'SURVEY': CAT_SURVEY,
    'INSTALLATION': CAT_INSTALLATION,
    'COMPLAINT': CAT_COMPLAINT,
    'MAINTENANCE': CAT_MAINTENANCE,
    'AMC': CAT_AMC,
    'UPGRADE': CAT_PROJECT,
}
