# Generated by Django 6.1.1 on 2026-09-20 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_alter_client_gst_type'),
        ('orders', '0004_order_source_and_operational_fields'),
        ('special_projects', '0001_special_projects_phase1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PMObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('site_location', models.CharField(blank=True, max_length=255, verbose_name='Site / Location')),
                ('system_service', models.CharField(blank=True, max_length=120, verbose_name='System / Service')),
                ('equipment_asset', models.CharField(blank=True, max_length=200, verbose_name='Equipment / Asset')),
                ('observation', models.TextField()),
                ('recommended_work', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('maintenance_type', models.CharField(choices=[('CORRECTIVE', 'Corrective'), ('PREVENTIVE', 'Preventive'), ('FUTURE', 'Future / Planned'), ('IMPROVEMENT', 'Improvement / Upgrade'), ('SAFETY', 'Safety / Compliance')], default='PREVENTIVE', max_length=20)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFORMATIONAL', 'Informational')], default='MEDIUM', max_length=20)),
                ('current_condition', models.CharField(blank=True, choices=[('WORKING_NORMAL', 'Working normally'), ('WORKING_ISSUE', 'Working with issue'), ('DEGRADED', 'Degraded'), ('AT_RISK', 'At risk of failure'), ('FAILED', 'Failed'), ('NOT_IN_USE', 'Not in use'), ('OBSOLETE', 'Obsolete'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('potential_impact', models.CharField(blank=True, choices=[('NO_IMMEDIATE', 'No immediate impact'), ('MINOR', 'Minor service impact'), ('PERFORMANCE', 'Performance degradation'), ('INTERRUPTION_RISK', 'Service interruption risk'), ('MAJOR_INTERRUPTION', 'Major service interruption'), ('SAFETY_RISK', 'Safety risk'), ('CUSTOMER_ESCALATION', 'Customer escalation risk')], max_length=30)),
                ('suggested_due_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('FIELD_VISIT', 'Field Visit'), ('PM_VISIT', 'Preventive Maintenance Visit'), ('BREAKDOWN_VISIT', 'Breakdown Visit'), ('CUSTOMER_COMPLAINT', 'Customer Complaint'), ('TECHNICIAN_OBSERVATION', 'Technician Observation'), ('ENGINEER_OBSERVATION', 'Engineer Observation'), ('TL_INSPECTION', 'TL Inspection'), ('PROJECT_SURVEY', 'Project Survey'), ('AMC_VISIT', 'AMC Visit'), ('MANAGEMENT_INSPECTION', 'Management Inspection'), ('OTHER', 'Other')], default='FIELD_VISIT', max_length=30)),
                ('admin_status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed')], db_index=True, default='REPORTED', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gps_address', models.CharField(blank=True, max_length=500)),
                ('gps_captured_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_observations_approved', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_observations', to='clients.client')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_observations_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_observations_created', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, help_text='Existing order/project visit this observation was captured on, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_pm_observations', to='orders.order')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_observations', to='special_projects.specialproject')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_observations_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PMObservationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('ORDER_CREATED', 'Order Created'), ('ORDER_LINKED', 'Order Linked'), ('PRIORITY_CHANGED', 'Priority Changed'), ('TYPE_CHANGED', 'Classification Changed'), ('CLOSED', 'Closed'), ('GPS_CAPTURED', 'GPS Captured'), ('SNAPSHOT', 'Snapshot Added')], max_length=30)),
                ('previous_value', models.CharField(blank=True, max_length=80)),
                ('new_value', models.CharField(blank=True, max_length=80)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_history_actions', to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='preventive_maintenance.pmobservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PMObservationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_item', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_orders_created', to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_links', to='preventive_maintenance.pmobservation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_order_links', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PMObservationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SNAPSHOT', 'Snapshot'), ('DOCUMENT', 'Document')], default='SNAPSHOT', max_length=20)),
                ('file', models.FileField(upload_to='preventive_maintenance/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='preventive_maintenance.pmobservation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_snapshots_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['captured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pmobservation',
            index=models.Index(fields=['admin_status', 'priority'], name='preventive__admin_s_9c4641_idx'),
        ),
        migrations.AddIndex(
            model_name='pmobservation',
            index=models.Index(fields=['suggested_due_date'], name='preventive__suggest_321029_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pmobservationorder',
            unique_together={('observation', 'order')},
        ),
    ]
