# Generated by Django 6.0.3 on 2026-06-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoice_amount_alter_invoice_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number_mode',
            field=models.CharField(choices=[('AUTO', 'Auto Generate'), ('MANUAL', 'Manual Entry')], default='AUTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
