# Generated by Django 6.0.3 on 2026-06-12 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_authorized_signatory_designation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_type',
            field=models.CharField(choices=[('INTRA_STATE', 'CGST + SGST (Intra-state)'), ('INTER_STATE', 'IGST (Inter-state)')], default='INTRA_STATE', max_length=15, verbose_name='GST Type'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='InvoiceGstAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_gst_type', models.CharField(blank=True, max_length=15)),
                ('previous_gst_type', models.CharField(blank=True, max_length=15)),
                ('new_gst_type', models.CharField(max_length=15)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_gst_audits', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_audit_logs', to='billing.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
