# Generated by Django 6.0.3 on 2026-06-12 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_existing_invoices_approved(apps, schema_editor):
    Invoice = apps.get_model('billing', 'Invoice')
    InvoiceApprovalAuditLog = apps.get_model('billing', 'InvoiceApprovalAuditLog')
    for invoice in Invoice.objects.all():
        if invoice.approval_status == 'DRAFT':
            invoice.approval_status = 'APPROVED'
            invoice.save(update_fields=['approval_status'])
            InvoiceApprovalAuditLog.objects.create(
                invoice=invoice,
                action='APPROVED',
                performed_by=None,
                previous_status='DRAFT',
                new_status='APPROVED',
                remarks='Auto-approved during invoice approval workflow migration.',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_backfill_invoice_gst_breakdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='approval_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('WRONG_GST', 'Wrong GST'), ('WRONG_CLIENT', 'Wrong Client'), ('WRONG_AMOUNT', 'Wrong Amount'), ('WRONG_BOQ', 'Wrong BOQ'), ('DUPLICATE', 'Duplicate Invoice'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gst_type',
            field=models.CharField(choices=[('INTRA_STATE', 'Intra-State (CGST + SGST)'), ('INTER_STATE', 'Inter-State (IGST)')], default='INTRA_STATE', max_length=15, verbose_name='GST Type'),
        ),
        migrations.CreateModel(
            name='InvoiceApprovalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted for Approval'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Resubmitted'), ('CANCELLED', 'Cancelled'), ('EDITED', 'Edited')], max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=15)),
                ('new_status', models.CharField(blank=True, max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=20)),
                ('notification_channel', models.CharField(blank=True, help_text='Reserved for future email/WhatsApp/mobile notifications', max_length=30)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_audit_logs', to='billing.invoice')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_approval_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(
            backfill_existing_invoices_approved,
            migrations.RunPython.noop,
        ),
    ]
