# Generated by Django 6.0.3 on 2026-07-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoice_approval_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceapprovalauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted for Approval'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Resubmitted'), ('CANCELLED', 'Cancelled'), ('EDITED', 'Edited'), ('UNLOCKED', 'Unlocked for Editing')], max_length=20),
        ),
    ]
