# Generated by Django 6.0.3 on 2026-07-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_intelligence', '0002_caseactivitylog_backfill_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='caseactivitylog',
            new_name='case_intell_module_3b83c3_idx',
            old_name='case_intell_module_4a8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='caseactivitylog',
            new_name='case_intell_documen_3b88d9_idx',
            old_name='case_intell_documen_8c3e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='caseactivitylog',
            new_name='case_intell_client__5ce9b0_idx',
            old_name='case_intell_client__9d2f4b_idx',
        ),
        migrations.RenameIndex(
            model_name='caseactivitylog',
            new_name='case_intell_activit_f0d0db_idx',
            old_name='case_intell_activit_1e7c3d_idx',
        ),
    ]
