# Generated by Django 6.1.1 on 2026-09-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_intelligence', '0003_rename_case_intell_module_4a8f2d_idx_case_intell_module_3b83c3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseactivitylog',
            name='module',
            field=models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('ESTIMATE_BOQ', 'Estimate BOQ'), ('QUOTATION', 'Quotation'), ('ORDER', 'Order'), ('SCHEDULE', 'Schedule'), ('WCR', 'WCR'), ('INVOICE', 'Invoice'), ('PAYMENT', 'Payment'), ('BOQ', 'BOQ'), ('PM_OBSERVATION', 'PM Observation')], db_index=True, max_length=20),
        ),
    ]
