"""Case intelligence module and health constants."""

MOD_ENQUIRY = 'ENQUIRY'
MOD_ESTIMATE_BOQ = 'ESTIMATE_BOQ'
MOD_QUOTATION = 'QUOTATION'
MOD_ORDER = 'ORDER'
MOD_SCHEDULE = 'SCHEDULE'
MOD_WCR = 'WCR'
MOD_INVOICE = 'INVOICE'
MOD_PAYMENT = 'PAYMENT'
MOD_BOQ = 'BOQ'
MOD_PM = 'PM_OBSERVATION'

MODULE_CHOICES = (
    (MOD_ENQUIRY, 'Enquiry'),
    (MOD_ESTIMATE_BOQ, 'Estimate BOQ'),
    (MOD_QUOTATION, 'Quotation'),
    (MOD_ORDER, 'Order'),
    (MOD_SCHEDULE, 'Schedule'),
    (MOD_WCR, 'WCR'),
    (MOD_INVOICE, 'Invoice'),
    (MOD_PAYMENT, 'Payment'),
    (MOD_BOQ, 'BOQ'),
    (MOD_PM, 'PM Observation'),
)

HEALTH_GREEN = 'GREEN'
HEALTH_YELLOW = 'YELLOW'
HEALTH_RED = 'RED'

HEALTH_LABELS = {
    HEALTH_GREEN: 'On Track',
    HEALTH_YELLOW: 'Attention Required',
    HEALTH_RED: 'Stuck / Overdue',
}

STUCK_ENQUIRY_INACTIVE = 'ENQUIRY_PENDING'
STUCK_SURVEY_DELAYED = 'SURVEY_DELAYED'
STUCK_QUOTATION = 'QUOTATION_STUCK'
STUCK_ORDER_SCHEDULE = 'EXECUTION_DELAYED'
STUCK_WCR = 'WCR_PENDING'
STUCK_INVOICE = 'INVOICE_APPROVAL_PENDING'
STUCK_PAYMENT = 'PAYMENT_FOLLOWUP'
