# Generated by Django 6.0.3 on 2026-06-06 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_signatory_name', models.CharField(blank=True, help_text='Name printed below Authorized Signatory on official documents.', max_length=100)),
                ('authorized_signatory_designation', models.CharField(blank=True, help_text='e.g. Director, Operations Head, Accounts Manager', max_length=100)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='company/signatures/')),
                ('company_seal', models.ImageField(blank=True, null=True, upload_to='company/seals/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company settings',
                'verbose_name_plural': 'Company settings',
            },
        ),
    ]
