# Generated by Django 6.0.3 on 2026-06-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0003_copy_signatory_to_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='authorized_signatory_designation',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='authorized_signatory_name',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='signature_image',
        ),
    ]
