# Generated by Django 6.0.3 on 2026-06-13 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0004_remove_companysettings_authorized_signatory_designation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOperationsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_tracking_enabled', models.BooleanField(default=True, verbose_name='GPS Tracking')),
                ('checkin_checkout_enabled', models.BooleanField(default=True, verbose_name='Site Check-In / Check-Out')),
                ('productivity_tracking_enabled', models.BooleanField(default=True, verbose_name='Productivity Tracking')),
                ('site_photos_enabled', models.BooleanField(default=True, verbose_name='Site Photo Uploads')),
                ('device_tracking_enabled', models.BooleanField(default=True, verbose_name='Device Information Tracking')),
                ('auto_survey_schedule_enabled', models.BooleanField(default=True, verbose_name='Auto-Create Survey Schedules')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_ops_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field operations settings',
                'verbose_name_plural': 'Field operations settings',
            },
        ),
    ]
