# Generated by Django 6.0.3 on 2026-07-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0007_caseintelligence_thresholds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseintelligencesettings',
            name='enquiry_delay_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Flag enquiry if no activity for this many days.', verbose_name='Enquiry delay days'),
        ),
        migrations.AlterField(
            model_name='caseintelligencesettings',
            name='enquiry_inactive_days',
            field=models.PositiveSmallIntegerField(default=7, editable=False),
        ),
        migrations.AlterField(
            model_name='caseintelligencesettings',
            name='invoice_approval_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Flag submitted invoice pending approval beyond this many days.', verbose_name='Invoice approval days'),
        ),
        migrations.AlterField(
            model_name='caseintelligencesettings',
            name='order_delay_days',
            field=models.PositiveSmallIntegerField(default=5, help_text='Flag order if no schedule created within this period.', verbose_name='Order delay days'),
        ),
        migrations.AlterField(
            model_name='caseintelligencesettings',
            name='order_schedule_delay_days',
            field=models.PositiveSmallIntegerField(default=5, editable=False),
        ),
        migrations.AlterField(
            model_name='caseintelligencesettings',
            name='payment_followup_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Days after due date before flagging payment follow-up (0 = on due date).', verbose_name='Payment follow-up days'),
        ),
        migrations.AlterField(
            model_name='caseintelligencesettings',
            name='quotation_followup_days',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Quotation follow-up days'),
        ),
        migrations.AlterField(
            model_name='caseintelligencesettings',
            name='survey_delay_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Days after scheduled survey date before flagging as delayed (0 = same day).', verbose_name='Survey delay days'),
        ),
        migrations.AlterField(
            model_name='caseintelligencesettings',
            name='wcr_delay_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Flag completed order if WCR not submitted within this period.', verbose_name='WCR delay days'),
        ),
        migrations.AlterField(
            model_name='caseintelligencesettings',
            name='wcr_submit_delay_days',
            field=models.PositiveSmallIntegerField(default=3, editable=False),
        ),
    ]
