# Generated by Django 6.0.3 on 2026-03-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('TELECOM', 'Telecom'), ('IT', 'IT Infrastructure'), ('CCTV', 'CCTV'), ('NETWORK', 'Networking'), ('WIFI', 'WiFi')], max_length=20)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
