# Generated by Django 6.0.3 on 2026-06-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='client',
            name='gst_type',
            field=models.CharField(blank=True, choices=[('', 'Auto (from state)'), ('INTRA_STATE', 'CGST + SGST (Intra-state)'), ('INTER_STATE', 'IGST (Inter-state)')], help_text='Leave blank to auto-apply CGST+SGST for Kerala, IGST for other states', max_length=15, verbose_name='GST Type'),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('', '— Select State —'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], help_text='Client state for GST determination', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='state_code',
            field=models.CharField(blank=True, help_text='GST state code (auto-filled from GSTIN when possible)', max_length=2, verbose_name='State Code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='GST Number'),
        ),
    ]
