# Generated by Django 6.0.3 on 2026-07-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gst_type',
            field=models.CharField(blank=True, choices=[('', 'Auto (from state)'), ('INTRA_STATE', 'Intra-State (CGST + SGST)'), ('INTER_STATE', 'Inter-State (IGST)')], help_text='Leave blank to auto-apply CGST+SGST for Kerala, IGST for other states', max_length=15, verbose_name='GST Type'),
        ),
    ]
