# Generated by Django 6.0.3 on 2026-05-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Director'), ('OPERATIONS', 'Operations Manager'), ('ACCOUNTS', 'Accounts Manager'), ('ENGINEER', 'Field Engineer'), ('Technician', 'Field Technician'), ('Supervisor', 'Field Supervisor')], max_length=20),
        ),
    ]
