# Generated by Django 6.0.3 on 2026-06-12 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_approval_status_user_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reports_to',
            field=models.ForeignKey(blank=True, help_text='Organizational reporting line (Director → Operations → PM → Supervisor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('DIRECTOR', 'Director'), ('OPERATIONS', 'Operations Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('SUPERVISOR', 'Supervisor'), ('ACCOUNTS', 'Accounts Manager'), ('ENGINEER', 'Field Engineer'), ('Technician', 'Field Technician'), ('Supervisor', 'Field Supervisor (Legacy)')], default='', max_length=20),
        ),
    ]
