# Generated by Django 6.0.3 on 2026-06-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_migrate_legacy_supervisor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('DIRECTOR', 'Director'), ('OPERATIONS', 'Operations Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('SUPERVISOR', 'Supervisor'), ('ACCOUNTS', 'Accounts Manager'), ('ACCOUNTS_EXECUTIVE', 'Accounts Executive'), ('BACK_OFFICE', 'Back Office Staff'), ('ENGINEER', 'Field Engineer'), ('Technician', 'Field Technician'), ('Supervisor', 'Field Supervisor (Legacy)')], default='', max_length=20),
        ),
    ]
