# Generated by Django 6.0.3 on 2026-06-13 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_choices_v12'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'codename'],
            },
        ),
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('hierarchy_level', models.PositiveSmallIntegerField(default=100, help_text='Lower number = higher authority (Admin=0, Director=10, …)')),
                ('is_system', models.BooleanField(default=True, help_text='System roles are seeded and should not be deleted.')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['hierarchy_level', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('DIRECTOR', 'Director'), ('OPERATIONS', 'Operations Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('SUPERVISOR', 'Project Supervisor'), ('ACCOUNTS', 'Accounts Manager'), ('ACCOUNTS_EXECUTIVE', 'Accounts Executive'), ('BACK_OFFICE', 'Back Office Staff'), ('ENGINEER', 'Field Engineer'), ('Technician', 'Field Technician'), ('Supervisor', 'Field Supervisor (Legacy)')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('url_name', models.CharField(blank=True, max_length=80)),
                ('icon', models.CharField(blank=True, default='bi-circle', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('nav_key', models.CharField(blank=True, help_text='Matches nav_active key in context processor (e.g. enquiries).', max_length=40)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.menuitem')),
                ('permission', models.ForeignKey(blank=True, help_text='User must have this permission to see the menu item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='accounts.systempermission')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ActionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=80)),
                ('url_pattern', models.CharField(blank=True, help_text='Path prefix, e.g. /enquiries/create/', max_length=200)),
                ('view_name', models.CharField(blank=True, max_length=80)),
                ('http_method', models.CharField(default='GET', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='accounts.systempermission')),
            ],
            options={
                'ordering': ['url_pattern'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.systempermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.systemrole')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
