# Generated by Django 6.0.3 on 2026-07-10 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from accounts.enterprise_migration import (
    migrate_users_to_employees,
    reverse_migrate_users,
    reverse_seed_masters,
    seed_masters,
)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_attendance_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('is_head_office', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['-is_head_office', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Department',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Designation',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('menu_url_name', models.CharField(blank=True, help_text='Django URL name for permission-driven menu (Phase 2).', max_length=80)),
                ('menu_icon', models.CharField(blank=True, default='bi-circle', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=True, help_text='System permissions are seeded and should not be deleted.')),
            ],
            options={
                'verbose_name': 'Module Permission',
                'ordering': ['sort_order', 'category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='attendance_required',
            field=models.BooleanField(default=True, help_text='When Yes, employee must mark daily attendance and sees the Attendance menu. Directors and Admins should be set to No. Editable by Super User only.'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=30, unique=True)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern'), ('CONSULTANT', 'Consultant')], default='FULL_TIME', max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='accounts.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='accounts.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='accounts.designation')),
                ('reporting_manager', models.ForeignKey(blank=True, help_text='Approval hierarchy uses reporting manager, not designation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_direct_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='accounts.employee')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_grants_given', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='accounts.modulepermission')),
            ],
            options={
                'ordering': ['permission__sort_order', 'permission__name'],
                'unique_together': {('employee', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='employees', through='accounts.EmployeePermissionGrant', to='accounts.modulepermission'),
        ),
        migrations.RunPython(seed_masters, reverse_seed_masters),
        migrations.RunPython(migrate_users_to_employees, reverse_migrate_users),
    ]
