# Generated by Django 6.0.3 on 2026-08-03 09:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_source_and_operational_fields'),
        ('special_projects', '0001_special_projects_phase1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetrolCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=120)),
                ('card_number', models.CharField(max_length=40, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_recharge_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['card_name'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Company Petty Cash', max_length=80)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Petty cash account',
            },
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('previous_odometer_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('current_odometer_km', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_odometer_km', models.DecimalField(blank=True, decimal_places=2, help_text='Optional; defaults to current reading.', max_digits=12, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fuel_quantity_litres', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fuel_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('mileage_kmpl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mileage (KM/L)')),
                ('payment_method', models.CharField(choices=[('DIRECT_CASH', 'Direct Cash (Reimbursement)'), ('PETTY_CASH', 'Petty Cash'), ('PETROL_CARD', 'Prepaid Petrol Card')], default='DIRECT_CASH', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('fuel_station', models.CharField(blank=True, max_length=200)),
                ('bill_number', models.CharField(blank=True, max_length=80)),
                ('bill_upload', models.FileField(blank=True, upload_to='fleet/fuel_bills/')),
                ('remarks', models.TextField(blank=True)),
                ('odometer_warning', models.BooleanField(default=False, help_text='True when current KM is not greater than previous KM.')),
                ('reimbursement_status', models.CharField(blank=True, choices=[('', '—'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='', max_length=15)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked after accounts approval/payment processing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Technician / Driver')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions', to='orders.order')),
                ('special_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions', to='special_projects.specialproject')),
                ('petrol_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions', to='fleet.petrolcard')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PetrolCardRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=80)),
                ('bank', models.CharField(blank=True, max_length=120)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='fleet.petrolcard')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petrol_card_recharges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recharge_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Credit / Top-up'), ('DEBIT', 'Debit / Fuel')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fleet.pettycashaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fuel_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_entries', to='fleet.fueltransaction')),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('TWO_WHEELER', 'Two Wheeler'), ('FOUR_WHEELER', 'Four Wheeler'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('OTHER', 'Other')], default='FOUR_WHEELER', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=80, verbose_name='Model')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('CNG', 'CNG'), ('EV', 'EV')], default='PETROL', max_length=15)),
                ('tank_capacity_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mileage_target_kmpl', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Average mileage target (KM/L)')),
                ('last_odometer_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Updated automatically from fuel entries.', max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Under Maintenance')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('puc_expiry', models.DateField(blank=True, null=True)),
                ('next_service_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.AddField(
            model_name='petrolcard',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petrol_cards', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_transactions', to='fleet.vehicle'),
        ),
    ]
