from django.urls import path
from . import views

urlpatterns = [
    path('', views.quotation_list, name='quotation_list'),
    path('create/', views.quotation_create, name='quotation_create'),
    path('from-enquiry/<int:enquiry_pk>/', views.quotation_create_from_enquiry, name='quotation_create_from_enquiry'),
    path('<int:pk>/', views.quotation_detail, name='quotation_detail'),
    path('<int:pk>/edit/', views.quotation_edit, name='quotation_edit'),
    path('<int:pk>/pdf/', views.quotation_pdf, name='quotation_pdf'),
    path('<int:pk>/print/', views.quotation_print, name='quotation_print'),
    path('<int:pk>/covering-letter/', views.covering_letter_preview, name='covering_letter_preview'),
    path('<int:pk>/covering-letter/print/', views.covering_letter_print, name='covering_letter_print'),
    path('settings/', views.quotation_settings, name='quotation_settings'),
    path('settings/covering-letter/', views.covering_letter_settings, name='covering_letter_settings'),
    path('templates/', views.proposal_template_list, name='proposal_template_list'),
    path('templates/add/', views.proposal_template_create, name='proposal_template_create'),
    path('templates/<int:pk>/edit/', views.proposal_template_edit, name='proposal_template_edit'),
    path('templates/<int:pk>/delete/', views.proposal_template_delete, name='proposal_template_delete'),
    path('templates/<int:pk>/duplicate/', views.proposal_template_duplicate, name='proposal_template_duplicate'),
    path('templates/<int:pk>/default/', views.proposal_template_set_default, name='proposal_template_set_default'),
    path('api/proposal-template/', views.proposal_template_api, name='proposal_template_api'),
    path('<int:pk>/submit-review/', views.quotation_submit_review, name='quotation_submit_review'),
    path('<int:pk>/approve/', views.quotation_approve, name='quotation_approve'),
    path('<int:pk>/sent/', views.quotation_mark_sent, name='quotation_mark_sent'),
    path('<int:pk>/accept/', views.quotation_accept, name='quotation_accept'),
    path('<int:pk>/reject/', views.quotation_reject, name='quotation_reject'),
    path('<int:pk>/convert/', views.quotation_convert_order, name='quotation_convert_order'),
    path('rates/service/', views.service_rate_list, name='service_rate_list'),
    path('rates/service/add/', views.service_rate_create, name='service_rate_create'),
    path('rates/service/<int:pk>/edit/', views.service_rate_edit, name='service_rate_edit'),
    path('rates/service/<int:pk>/delete/', views.service_rate_delete, name='service_rate_delete'),
    path('rates/material/', views.material_rate_list, name='material_rate_list'),
    path('rates/material/add/', views.material_rate_create, name='material_rate_create'),
    path('rates/material/<int:pk>/edit/', views.material_rate_edit, name='material_rate_edit'),
    path('rates/material/<int:pk>/delete/', views.material_rate_delete, name='material_rate_delete'),
    path('rates/audit/', views.rate_audit_list, name='rate_audit_list'),
    path('api/rate-card/', views.rate_card_api, name='rate_card_api'),
]
