# Generated by Django 6.0.3 on 2026-08-03 08:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_source_and_operational_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('site_location', models.CharField(blank=True, max_length=255)),
                ('work_description', models.TextField()),
                ('daily_progress_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('planned_work', models.TextField(blank=True)),
                ('actual_work', models.TextField(blank=True)),
                ('issues_risks', models.TextField(blank=True)),
                ('next_day_plan', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_employees', models.ManyToManyField(blank=True, related_name='special_project_daily_assignments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_project_logs_created', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_project_logs_as_mentor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Daily Log',
                'ordering': ['-log_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailyServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('CABLE_LAYING', 'Cable Laying'), ('SPLICING', 'Splicing'), ('TERMINATION', 'Termination'), ('TESTING', 'Testing'), ('INSTALLATION', 'Installation'), ('SURVEY', 'Survey'), ('CONFIGURATION', 'Configuration'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('unit', models.CharField(default='Nos', max_length=30)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='special_projects.projectdailylog')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('BEFORE', 'Before photo'), ('DURING', 'During work photo'), ('AFTER', 'After photo'), ('DRAWING', 'Drawing'), ('DOCUMENT', 'Document')], default='DURING', max_length=20)),
                ('file', models.FileField(upload_to='special_projects/media/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='special_projects.projectdailylog')),
            ],
            options={
                'verbose_name_plural': 'Daily media',
                'ordering': ['media_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyMaterialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200)),
                ('unit', models.CharField(default='Nos', max_length=30)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('issued_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('consumed_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('returned_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('linked_boq_item', models.CharField(blank=True, help_text='BOQ line reference (text for Phase 1)', max_length=120)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_lines', to='special_projects.projectdailylog')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyLabourLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave')], default='PRESENT', max_length=15)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('special_work', models.CharField(blank=True, max_length=255)),
                ('emergency_callout', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_project_labour_lines', to=settings.AUTH_USER_MODEL)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_lines', to='special_projects.projectdailylog')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyExpenseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('FUEL', 'Fuel'), ('FOOD', 'Food'), ('ACCOMMODATION', 'Accommodation'), ('LOCAL_TRANSPORT', 'Local Transport'), ('PARKING', 'Parking'), ('TOLL', 'Toll'), ('COURIER', 'Courier'), ('EQUIPMENT_HIRE', 'Equipment Hire'), ('MISC', 'Miscellaneous')], default='MISC', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('bill_photo', models.FileField(blank=True, upload_to='special_projects/expense_bills/')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='special_projects.projectdailylog')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SpecialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('OFC', 'OFC / Fibre'), ('NETWORK', 'Networking'), ('CCTV', 'CCTV / ELV'), ('ISP', 'ISP Installation'), ('INFRA', 'IT Infrastructure'), ('MAINTENANCE', 'Long Maintenance'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='PLANNING', max_length=20)),
                ('overall_progress_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0–100', max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_projects_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_project', to='orders.order')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_projects_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Special Project',
                'verbose_name_plural': 'Special Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectdailylog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='special_projects.specialproject'),
        ),
        migrations.AlterUniqueTogether(
            name='projectdailylog',
            unique_together={('project', 'log_date')},
        ),
    ]
