# Generated by Django 6.0.3 on 2026-06-12 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0003_order_expected_completion_date_order_order_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('enquiry_date', models.DateField(default=django.utils.timezone.now)),
                ('contact_person', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.TextField()),
                ('enquiry_type', models.CharField(choices=[('SURVEY', 'Survey'), ('INSTALLATION', 'Installation'), ('COMPLAINT', 'Complaint'), ('MAINTENANCE', 'Maintenance'), ('AMC', 'AMC'), ('UPGRADE', 'Upgrade')], max_length=20)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('PHONE', 'Phone Call'), ('EMAIL', 'Email'), ('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('WALK_IN', 'Walk-in'), ('EXISTING_CLIENT', 'Existing Client'), ('OTHER', 'Other')], default='PHONE', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('SURVEY_SCHEDULED', 'Survey Scheduled'), ('SURVEY_COMPLETED', 'Survey Completed'), ('FEASIBILITY_IN_PROGRESS', 'Feasibility In Progress'), ('QUOTATION_PREPARATION', 'Quotation Preparation'), ('QUOTATION_SUBMITTED', 'Quotation Submitted'), ('FOLLOW_UP', 'Follow Up'), ('WON', 'Won'), ('LOST', 'Lost'), ('CLOSED', 'Closed'), ('CONVERTED_TO_ORDER', 'Converted To Order')], default='NEW', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('survey_required', models.BooleanField(default=True)),
                ('feasibility_required', models.BooleanField(default=True)),
                ('survey_date', models.DateField(blank=True, null=True)),
                ('survey_remarks', models.TextField(blank=True)),
                ('feasibility_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('FEASIBLE', 'Feasible'), ('NOT_FEASIBLE', 'Not Feasible'), ('ON_HOLD', 'On Hold')], default='PENDING', max_length=20)),
                ('feasibility_remarks', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('opportunity_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('lead_source_detail', models.CharField(blank=True, max_length=200)),
                ('meeting_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('amc_reference', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_as_pm', to=settings.AUTH_USER_MODEL)),
                ('assigned_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_as_supervisor', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_assigned', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='clients.client')),
                ('converted_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_enquiry', to='orders.order')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_created', to=settings.AUTH_USER_MODEL)),
                ('survey_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_surveyed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-enquiry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(default=django.utils.timezone.now)),
                ('site_location', models.CharField(blank=True, max_length=200)),
                ('work_description', models.TextField()),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='site_progress/')),
                ('attendance_noted', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_updates', to='enquiries.enquiry')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_updates', to='orders.order')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_progress_updates', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_updates_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-update_date', '-created_at'],
            },
        ),
    ]
