"""ERMS status and type constants."""

STATUS_DRAFT = 'DRAFT'
STATUS_SUBMITTED = 'SUBMITTED'
STATUS_UNDER_REVIEW = 'UNDER_REVIEW'
STATUS_APPROVED = 'APPROVED'
STATUS_REJECTED = 'REJECTED'
STATUS_RETURNED = 'RETURNED'
STATUS_COMPLETED = 'COMPLETED'
STATUS_CANCELLED = 'CANCELLED'

STATUS_CHOICES = (
    (STATUS_DRAFT, 'Draft'),
    (STATUS_SUBMITTED, 'Submitted'),
    (STATUS_UNDER_REVIEW, 'Under Review'),
    (STATUS_APPROVED, 'Approved'),
    (STATUS_REJECTED, 'Rejected'),
    (STATUS_RETURNED, 'Returned for Correction'),
    (STATUS_COMPLETED, 'Completed'),
    (STATUS_CANCELLED, 'Cancelled'),
)

PENDING_STATUSES = (STATUS_SUBMITTED, STATUS_UNDER_REVIEW)
TERMINAL_STATUSES = (STATUS_APPROVED, STATUS_REJECTED, STATUS_COMPLETED, STATUS_CANCELLED)
EDITABLE_STATUSES = (STATUS_DRAFT, STATUS_RETURNED)

PRIORITY_LOW = 'LOW'
PRIORITY_NORMAL = 'NORMAL'
PRIORITY_HIGH = 'HIGH'
PRIORITY_URGENT = 'URGENT'

PRIORITY_CHOICES = (
    (PRIORITY_LOW, 'Low'),
    (PRIORITY_NORMAL, 'Normal'),
    (PRIORITY_HIGH, 'High'),
    (PRIORITY_URGENT, 'Urgent'),
)

# Financial request types — require erms_financial_approve for accounts roles.
FINANCIAL_TYPE_CODES = frozenset({
    'PURCHASE', 'REIMBURSEMENT', 'PETTY_CASH', 'MATERIAL',
})

ALLOWED_EXTENSIONS = ('pdf', 'jpg', 'jpeg', 'png', 'docx', 'xlsx')
MAX_ATTACHMENT_MB = 10

DEFAULT_REQUEST_TYPES = (
    ('LEAVE', 'Leave Request', False, 'SUPERVISOR,PROJECT_MANAGER,OPERATIONS'),
    ('PURCHASE', 'Purchase Request', True, 'ACCOUNTS,OPERATIONS,DIRECTOR'),
    ('REIMBURSEMENT', 'Reimbursement Request', True, 'ACCOUNTS,OPERATIONS'),
    ('PETTY_CASH', 'Petty Cash Request', True, 'ACCOUNTS'),
    ('MATERIAL', 'Material Request', True, 'PROJECT_MANAGER,OPERATIONS'),
    ('TOOL', 'Tool Request', False, 'PROJECT_MANAGER,OPERATIONS,SUPERVISOR'),
    ('GENERAL', 'General Request', False, 'OPERATIONS,PROJECT_MANAGER,DIRECTOR'),
)
