# Generated by Django 6.0.3 on 2026-06-13 11:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System items are re-seeded if missing.')),
            ],
            options={
                'verbose_name': 'Agenda template item',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DailyMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('meeting_date', models.DateField(db_index=True)),
                ('meeting_time', models.TimeField()),
                ('meeting_type', models.CharField(choices=[('DAILY', 'Daily Morning Meeting'), ('WEEKLY', 'Weekly Review'), ('SPECIAL', 'Special Meeting')], default='DAILY', max_length=20)),
                ('topic_of_day', models.CharField(blank=True, max_length=300)),
                ('department', models.CharField(blank=True, default='Operations', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('closing_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_conducted', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-meeting_date', '-meeting_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyMeetingsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_start_time', models.TimeField(default='09:00')),
                ('default_meeting_type', models.CharField(default='DAILY', max_length=20)),
                ('late_grace_minutes', models.PositiveSmallIntegerField(default=0, help_text='Minutes after start time before marking late.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dom_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily meetings settings',
                'verbose_name_plural': 'Daily meetings settings',
            },
        ),
        migrations.CreateModel(
            name='ManagementMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('category', models.CharField(choices=[('MOTIVATION', 'Motivation'), ('SAFETY', 'Safety'), ('QUALITY', 'Quality'), ('OPERATIONS', 'Operations'), ('HR', 'HR'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_messages_created', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_messages', to='daily_meetings.dailymeeting')),
            ],
            options={
                'ordering': ['-message_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='daily_meetings.dailymeeting')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_snapshot', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], db_index=True, default='ABSENT', max_length=12)),
                ('join_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('attendance_record_id', models.PositiveIntegerField(blank=True, help_text='Linked attendance.models.Attendance pk if auto-matched.', null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendance', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='daily_meetings.dailymeeting')),
            ],
            options={
                'ordering': ['employee__username'],
            },
        ),
        migrations.CreateModel(
            name='MeetingDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_title', models.CharField(max_length=200)),
                ('discussion_notes', models.TextField(blank=True)),
                ('key_learnings', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('improvement_areas', models.TextField(blank=True)),
                ('decisions_taken', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('agenda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='daily_meetings.meetingagendaitem')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='daily_meetings.dailymeeting')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='OpenItemRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_open_items', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_open_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MeetingOpenItemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_at_meeting', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_item_reviews', to='daily_meetings.dailymeeting')),
                ('open_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_reviews', to='daily_meetings.openitemregister')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('description', models.TextField()),
                ('target_date', models.DateField(blank=True, db_index=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], db_index=True, default='OPEN', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_meeting_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meeting_actions', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='daily_meetings.dailymeeting')),
                ('open_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='daily_meetings.openitemregister')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailymeeting',
            constraint=models.UniqueConstraint(fields=('meeting_date', 'meeting_type', 'department'), name='unique_daily_meeting_per_day_type_dept'),
        ),
        migrations.AddConstraint(
            model_name='meetingattendance',
            constraint=models.UniqueConstraint(fields=('meeting', 'employee'), name='unique_meeting_attendee'),
        ),
        migrations.AddConstraint(
            model_name='meetingopenitemsnapshot',
            constraint=models.UniqueConstraint(fields=('meeting', 'open_item'), name='unique_meeting_open_item'),
        ),
    ]
