# Generated by Django 6.0.3 on 2026-06-12 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateBOQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_boq_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_boqs_created', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_boqs', to='enquiries.enquiry')),
            ],
            options={
                'verbose_name': 'Estimate BOQ',
                'verbose_name_plural': 'Estimate BOQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateBOQLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.PositiveIntegerField()),
                ('item', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='Nos', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimate_boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='estimate_boq.estimateboq')),
            ],
            options={
                'ordering': ['sl_no'],
                'unique_together': {('estimate_boq', 'sl_no')},
            },
        ),
    ]
