"""Activity types and departments — extensible for future KPI/incentive modules."""

DEPT_OPERATIONS = 'OPERATIONS'
DEPT_PROJECTS = 'PROJECTS'
DEPT_ACCOUNTS = 'ACCOUNTS'
DEPT_ADMIN = 'ADMINISTRATION'
DEPT_FIELD = 'FIELD'

DEPARTMENT_CHOICES = (
    (DEPT_OPERATIONS, 'Operations'),
    (DEPT_PROJECTS, 'Projects'),
    (DEPT_ACCOUNTS, 'Accounts'),
    (DEPT_ADMIN, 'Administration'),
    (DEPT_FIELD, 'Field Operations'),
)

# Operations
ACT_ENQUIRY_PROCESSED = 'ENQUIRY_PROCESSED'
ACT_SURVEY_SCHEDULED = 'SURVEY_SCHEDULED'
ACT_SCHEDULE_CREATED = 'SCHEDULE_CREATED'
ACT_WCR_VERIFIED = 'WCR_VERIFIED'
ACT_CLIENT_FOLLOWUP = 'CLIENT_FOLLOWUP'

# Projects
ACT_ESTIMATE_BOQ = 'ESTIMATE_BOQ_PREPARED'
ACT_QUOTATION_CREATED = 'QUOTATION_CREATED'
ACT_EXECUTION_BOQ = 'EXECUTION_BOQ_PREPARED'
ACT_ORDER_PROCESSED = 'ORDER_PROCESSED'

# Accounts
ACT_INVOICE_CREATED = 'INVOICE_CREATED'
ACT_INVOICE_VERIFIED = 'INVOICE_VERIFIED'
ACT_INVOICE_APPROVED = 'INVOICE_APPROVED'
ACT_PAYMENT_FOLLOWUP = 'PAYMENT_FOLLOWUP'
ACT_PAYMENT_RECEIVED = 'PAYMENT_RECEIVED'

# Administration
ACT_USER_APPROVAL = 'USER_APPROVAL'
ACT_ATTENDANCE_REVIEW = 'ATTENDANCE_REVIEW'
ACT_REPORT_GENERATED = 'REPORT_GENERATED'

# Field
ACT_WCR_SUBMITTED = 'WCR_SUBMITTED'
ACT_JOB_ATTENDED = 'JOB_ATTENDED'

ACTIVITY_CHOICES = (
    (ACT_ENQUIRY_PROCESSED, 'Enquiry Processed'),
    (ACT_SURVEY_SCHEDULED, 'Survey Scheduled'),
    (ACT_SCHEDULE_CREATED, 'Schedule Created'),
    (ACT_WCR_VERIFIED, 'WCR Verified'),
    (ACT_CLIENT_FOLLOWUP, 'Client Follow-up'),
    (ACT_ESTIMATE_BOQ, 'Estimate BOQ Prepared'),
    (ACT_QUOTATION_CREATED, 'Quotation Created'),
    (ACT_EXECUTION_BOQ, 'Execution BOQ Prepared'),
    (ACT_ORDER_PROCESSED, 'Order Processed'),
    (ACT_INVOICE_CREATED, 'Invoice Created'),
    (ACT_INVOICE_VERIFIED, 'Invoice Submitted for Approval'),
    (ACT_INVOICE_APPROVED, 'Invoice Approved'),
    (ACT_PAYMENT_FOLLOWUP, 'Payment Follow-up'),
    (ACT_PAYMENT_RECEIVED, 'Payment Received'),
    (ACT_USER_APPROVAL, 'User Approval'),
    (ACT_ATTENDANCE_REVIEW, 'Attendance Review'),
    (ACT_REPORT_GENERATED, 'Report Generated'),
    (ACT_WCR_SUBMITTED, 'WCR Submitted'),
    (ACT_JOB_ATTENDED, 'Job Attended'),
)

ACTIVITY_DEPARTMENT = {
    ACT_ENQUIRY_PROCESSED: DEPT_OPERATIONS,
    ACT_SURVEY_SCHEDULED: DEPT_OPERATIONS,
    ACT_SCHEDULE_CREATED: DEPT_OPERATIONS,
    ACT_WCR_VERIFIED: DEPT_OPERATIONS,
    ACT_CLIENT_FOLLOWUP: DEPT_OPERATIONS,
    ACT_ESTIMATE_BOQ: DEPT_PROJECTS,
    ACT_QUOTATION_CREATED: DEPT_PROJECTS,
    ACT_EXECUTION_BOQ: DEPT_PROJECTS,
    ACT_ORDER_PROCESSED: DEPT_PROJECTS,
    ACT_INVOICE_CREATED: DEPT_ACCOUNTS,
    ACT_INVOICE_VERIFIED: DEPT_ACCOUNTS,
    ACT_INVOICE_APPROVED: DEPT_ACCOUNTS,
    ACT_PAYMENT_FOLLOWUP: DEPT_ACCOUNTS,
    ACT_PAYMENT_RECEIVED: DEPT_ACCOUNTS,
    ACT_USER_APPROVAL: DEPT_ADMIN,
    ACT_ATTENDANCE_REVIEW: DEPT_ADMIN,
    ACT_REPORT_GENERATED: DEPT_ADMIN,
    ACT_WCR_SUBMITTED: DEPT_FIELD,
    ACT_JOB_ATTENDED: DEPT_FIELD,
}

PARTICIPANT_PM = 'PROJECT_MANAGER'
PARTICIPANT_SUPERVISOR = 'SUPERVISOR'
PARTICIPANT_LEAD_ENGINEER = 'LEAD_ENGINEER'
PARTICIPANT_SUPPORTING_ENGINEER = 'SUPPORTING_ENGINEER'
PARTICIPANT_TECHNICIAN = 'TECHNICIAN'

PARTICIPANT_ROLE_CHOICES = (
    (PARTICIPANT_PM, 'Project Manager'),
    (PARTICIPANT_SUPERVISOR, 'Supervisor'),
    (PARTICIPANT_LEAD_ENGINEER, 'Lead Engineer'),
    (PARTICIPANT_SUPPORTING_ENGINEER, 'Supporting Engineer'),
    (PARTICIPANT_TECHNICIAN, 'Technician'),
)

COMPLETION_COMPLETED = 'COMPLETED'
COMPLETION_PARTIAL = 'PARTIAL'
COMPLETION_PENDING = 'PENDING'

COMPLETION_STATUS_CHOICES = (
    (COMPLETION_COMPLETED, 'Completed'),
    (COMPLETION_PARTIAL, 'Partially Completed'),
    (COMPLETION_PENDING, 'Pending'),
)
