"""Field action types for GPS capture and Field Activity Log."""

# Orders
FA_ORDER_ASSIGNED = 'ORDER_ASSIGNED'
FA_ORDER_IN_PROGRESS = 'ORDER_IN_PROGRESS'
FA_ORDER_ON_HOLD = 'ORDER_ON_HOLD'
FA_ORDER_COMPLETED = 'ORDER_COMPLETED'
FA_ORDER_CANCELLED = 'ORDER_CANCELLED'
FA_ORDER_CLOSED = 'ORDER_CLOSED'

# Schedules
FA_SCHEDULE_STARTED = 'SCHEDULE_STARTED'
FA_SCHEDULE_COMPLETED = 'SCHEDULE_COMPLETED'

# Surveys (enquiries)
FA_SURVEY_STARTED = 'SURVEY_STARTED'
FA_SURVEY_COMPLETED = 'SURVEY_COMPLETED'

# WCR
FA_WCR_DRAFT = 'WCR_DRAFT'
FA_WCR_SUBMITTED = 'WCR_SUBMITTED'
FA_WCR_APPROVED = 'WCR_APPROVED'

# Site attendance
FA_SURVEY_ASSIGNED = 'SURVEY_ASSIGNED'
FA_SITE_CHECK_IN = 'SITE_CHECK_IN'
FA_SITE_CHECK_OUT = 'SITE_CHECK_OUT'

FIELD_ACTION_CHOICES = (
    (FA_ORDER_ASSIGNED, 'Order Assigned'),
    (FA_ORDER_IN_PROGRESS, 'Order In Progress'),
    (FA_ORDER_ON_HOLD, 'Order On Hold'),
    (FA_ORDER_COMPLETED, 'Order Completed'),
    (FA_ORDER_CANCELLED, 'Order Cancelled'),
    (FA_ORDER_CLOSED, 'Order Closed'),
    (FA_SCHEDULE_STARTED, 'Schedule Started'),
    (FA_SCHEDULE_COMPLETED, 'Schedule Completed'),
    (FA_SURVEY_STARTED, 'Survey Started'),
    (FA_SURVEY_COMPLETED, 'Survey Completed'),
    (FA_WCR_DRAFT, 'WCR Draft Saved'),
    (FA_WCR_SUBMITTED, 'WCR Submitted'),
    (FA_WCR_APPROVED, 'WCR Approved'),
    (FA_SURVEY_ASSIGNED, 'Survey Assigned'),
    (FA_SITE_CHECK_IN, 'Site Check-In'),
    (FA_SITE_CHECK_OUT, 'Site Check-Out'),
)

ORDER_STATUS_TO_ACTION = {
    'SCHEDULED': FA_ORDER_ASSIGNED,
    'IN_PROGRESS': FA_ORDER_IN_PROGRESS,
    'COMPLETED': FA_ORDER_COMPLETED,
    'CLOSED': FA_ORDER_CLOSED,
}

SURVEY_STATUS_TO_ACTION = {
    'SURVEY_SCHEDULED': FA_SURVEY_STARTED,
    'SURVEY_COMPLETED': FA_SURVEY_COMPLETED,
}

SCHEDULE_STATUS_TO_ACTION = {
    'IN_PROGRESS': FA_SCHEDULE_STARTED,
    'COMPLETED': FA_SCHEDULE_COMPLETED,
}
