from django.urls import path
from . import views

urlpatterns = [
    path('', views.dom_dashboard, name='dom_dashboard'),
    path('meetings/', views.meeting_list, name='dom_meeting_list'),
    path('meetings/create/', views.meeting_create, name='dom_meeting_create'),
    path('meetings/today/', views.meeting_today, name='dom_meeting_today'),
    path('meetings/<int:pk>/', views.meeting_detail, name='dom_meeting_detail'),
    path('meetings/<int:pk>/edit/', views.meeting_edit, name='dom_meeting_edit'),
    path('meetings/<int:pk>/complete/', views.meeting_complete, name='dom_meeting_complete'),
    path('meetings/<int:pk>/sync-attendance/', views.meeting_sync_attendance, name='dom_meeting_sync_attendance'),
    path('meetings/<int:pk>/attendance/<int:att_pk>/edit/', views.meeting_attendance_edit, name='dom_meeting_attendance_edit'),
    path('meetings/<int:pk>/discussion/add/', views.discussion_add, name='dom_discussion_add'),
    path('meetings/<int:pk>/message/add/', views.message_add, name='dom_message_add'),
    path('meetings/<int:pk>/action/add/', views.action_add, name='dom_action_add_meeting'),
    path('meetings/<int:pk>/mom/print/', views.mom_print, name='dom_mom_print'),
    path('meetings/<int:pk>/mom/pdf/', views.mom_pdf, name='dom_mom_pdf'),
    path('calendar/', views.meeting_calendar, name='dom_calendar'),
    path('actions/', views.action_tracker, name='dom_action_tracker'),
    path('actions/add/', views.action_add, name='dom_action_add'),
    path('actions/<int:pk>/edit/', views.action_edit, name='dom_action_edit'),
    path('open-items/', views.open_items_list, name='dom_open_items'),
    path('open-items/create/', views.open_item_create, name='dom_open_item_create'),
    path('open-items/<int:pk>/edit/', views.open_item_edit, name='dom_open_item_edit'),
    path('agenda-template/', views.agenda_template_list, name='dom_agenda_template'),
    path('agenda-template/<int:pk>/edit/', views.agenda_template_edit, name='dom_agenda_template_edit'),
    path('reports/', views.reports_index, name='dom_reports'),
    path('reports/register/', views.report_register, name='dom_report_register'),
    path('reports/attendance/', views.report_attendance, name='dom_report_attendance'),
    path('reports/late-attendance/', views.report_late_attendance, name='dom_report_late'),
    path('reports/actions/', views.report_actions, name='dom_report_actions'),
    path('reports/open-items/', views.report_open_items, name='dom_report_open_items'),
    path('reports/effectiveness/', views.report_effectiveness, name='dom_report_effectiveness'),
    path('reports/messages/', views.report_messages, name='dom_report_messages'),
]
