# Generated by Django 6.0.3 on 2026-08-03 09:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('orders', '0004_order_source_and_operational_fields'),
        ('special_projects', '0001_special_projects_phase1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_code', models.CharField(choices=[('MANAGER', 'Manager'), ('ACCOUNTS', 'Accounts'), ('DIRECTOR', 'Director')], max_length=20)),
                ('step_order', models.PositiveSmallIntegerField(default=10)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for unlimited. Step applies when amount >= min and (<= max if set).', max_digits=12, null=True)),
                ('can_approve_up_to', models.DecimalField(blank=True, decimal_places=2, help_text='Approver at this step may approve up to this amount; blank = unlimited.', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['step_order', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('gl_account_code', models.CharField(blank=True, max_length=40)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Expense categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PeamsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_approval_threshold', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Expenses at or above this amount require Director approval.', max_digits=12)),
                ('default_currency', models.CharField(default='INR', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PEAMS settings',
                'verbose_name_plural': 'PEAMS settings',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('advance_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('purpose', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ADJUSTED', 'Adjusted'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('accounts_voucher_ref', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_advances', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_issued', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_advances', to='orders.order')),
                ('special_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='special_projects.specialproject')),
            ],
            options={
                'ordering': ['-advance_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('PERSONAL_CASH', 'Employee Personal Cash (Reimbursement)'), ('AGAINST_ADVANCE', 'Against Employee Advance'), ('BANK_TRANSFER', 'Company Bank Transfer'), ('PETROL_CARD', 'Prepaid Petrol Card (Fleet)'), ('CREDIT_CARD', 'Company Credit Card (Future)')], default='PERSONAL_CASH', max_length=20)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('bill_upload', models.FileField(blank=True, upload_to='project_expenses/bills/')),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MANAGER_REVIEW', 'Manager Review'), ('ACCOUNTS_REVIEW', 'Accounts Review'), ('DIRECTOR_REVIEW', 'Director Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Payment Released'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=20)),
                ('current_step', models.CharField(blank=True, max_length=20)),
                ('reimbursement_status', models.CharField(blank=True, choices=[('', '—'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='', max_length=15)),
                ('is_posted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('accounts_voucher_ref', models.CharField(blank=True, max_length=60)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tds_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_order_ref', models.CharField(blank=True, max_length=60)),
                ('opms_activity_ref', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_adjustments', to='project_expenses.employeeadvance')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='project_expenses.expensecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peams_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_expenses', to=settings.AUTH_USER_MODEL)),
                ('fuel_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peams_expenses', to='fleet.fueltransaction')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peams_expenses', to='orders.order')),
                ('special_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peams_expenses', to='special_projects.specialproject')),
            ],
            options={
                'ordering': ['-expense_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('txn_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('txn_type', models.CharField(choices=[('ADVANCE_ISSUE', 'Advance issued'), ('ADVANCE_ADJUST', 'Advance adjusted (expense)'), ('ADVANCE_SETTLE', 'Advance settled / returned'), ('EXPENSE', 'Project expense'), ('SP_DAILY_SYNC', 'Special Project daily expense sync'), ('FLEET_FUEL_REF', 'Fleet fuel cost reference'), ('REIMBURSEMENT_PAY', 'Reimbursement payment')], db_index=True, max_length=30)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('project_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_void', models.BooleanField(default=False)),
                ('accounts_voucher_ref', models.CharField(blank=True, max_length=60)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tds_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('cost_center', models.CharField(blank=True, max_length=60)),
                ('payroll_period', models.CharField(blank=True, max_length=20)),
                ('opms_activity_ref', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='project_expenses.employeeadvance')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='project_expenses.expensecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peams_ledger_created', to=settings.AUTH_USER_MODEL)),
                ('daily_expense_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peams_ledger', to='special_projects.dailyexpenseline')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peams_ledger', to=settings.AUTH_USER_MODEL)),
                ('fuel_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peams_ledger', to='fleet.fueltransaction')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peams_ledger', to='orders.order')),
                ('special_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peams_ledger', to='special_projects.specialproject')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='project_expenses.projectexpense')),
            ],
            options={
                'ordering': ['txn_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submitted'), ('APPROVE', 'Approved step'), ('REJECT', 'Rejected'), ('RETURN', 'Returned'), ('PAY', 'Payment released')], max_length=15)),
                ('step_code', models.CharField(blank=True, max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='project_expenses.projectexpense')),
            ],
            options={
                'ordering': ['-acted_at'],
            },
        ),
    ]
