# Generated by Django 6.0.3 on 2026-06-06 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ORDER', 'Order'), ('QUOTATION', 'Quotation'), ('WCR', 'Work Completion Report'), ('BOQ', 'BOQ'), ('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase Order')], max_length=20)),
                ('year_series', models.CharField(max_length=4)),
                ('last_serial', models.PositiveIntegerField(default=0)),
                ('last_number', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['document_type', '-year_series'],
                'unique_together': {('document_type', 'year_series')},
            },
        ),
        migrations.CreateModel(
            name='DocumentNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_prefix', models.CharField(default='ITSPL', max_length=10)),
                ('order_prefix', models.CharField(default='ORD', max_length=10)),
                ('quotation_prefix', models.CharField(default='QT', max_length=10)),
                ('wcr_prefix', models.CharField(default='WCR', max_length=10)),
                ('boq_prefix', models.CharField(default='BOQ', max_length=10)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('purchase_order_prefix', models.CharField(default='PO', max_length=10)),
                ('serial_length', models.PositiveSmallIntegerField(default=4)),
                ('year_format', models.CharField(default='YYYY', max_length=10)),
                ('allow_editing', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_number_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document number settings',
                'verbose_name_plural': 'Document number settings',
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocumentNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ORDER', 'Order'), ('QUOTATION', 'Quotation'), ('WCR', 'Work Completion Report'), ('BOQ', 'BOQ'), ('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase Order')], max_length=20)),
                ('document_number', models.CharField(max_length=50, unique=True)),
                ('year_series', models.CharField(max_length=4)),
                ('serial', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_document_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
