# Generated by Django 6.0.3 on 2026-06-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentnumbersettings',
            name='schedule_prefix',
            field=models.CharField(default='SCH', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentcounter',
            name='document_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('QUOTATION', 'Quotation'), ('WCR', 'Work Completion Report'), ('BOQ', 'BOQ'), ('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase Order'), ('SCHEDULE', 'Work Schedule')], max_length=20),
        ),
        migrations.AlterField(
            model_name='generateddocumentnumber',
            name='document_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('QUOTATION', 'Quotation'), ('WCR', 'Work Completion Report'), ('BOQ', 'BOQ'), ('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase Order'), ('SCHEDULE', 'Work Schedule')], max_length=20),
        ),
    ]
