# Generated by Django 6.0.3 on 2026-06-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0002_documentnumbersettings_schedule_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentnumbersettings',
            name='enquiry_prefix',
            field=models.CharField(default='ENQ', max_length=10),
        ),
        migrations.AddField(
            model_name='documentnumbersettings',
            name='estimate_boq_prefix',
            field=models.CharField(default='EBOQ', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentcounter',
            name='document_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('QUOTATION', 'Quotation'), ('WCR', 'Work Completion Report'), ('BOQ', 'BOQ'), ('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase Order'), ('SCHEDULE', 'Work Schedule'), ('ENQUIRY', 'Enquiry'), ('ESTIMATE_BOQ', 'Estimate BOQ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='generateddocumentnumber',
            name='document_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('QUOTATION', 'Quotation'), ('WCR', 'Work Completion Report'), ('BOQ', 'BOQ'), ('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase Order'), ('SCHEDULE', 'Work Schedule'), ('ENQUIRY', 'Enquiry'), ('ESTIMATE_BOQ', 'Estimate BOQ')], max_length=20),
        ),
    ]
