# Generated by Django 6.0.3 on 2026-08-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0005_invoice_prefix_blank_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentnumbersettings',
            name='special_project_prefix',
            field=models.CharField(default='SP', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentcounter',
            name='document_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('QUOTATION', 'Quotation'), ('WCR', 'Work Completion Report'), ('BOQ', 'BOQ'), ('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase Order'), ('SCHEDULE', 'Work Schedule'), ('ENQUIRY', 'Enquiry'), ('ESTIMATE_BOQ', 'Estimate BOQ'), ('REQUEST', 'Employee Request'), ('SPECIAL_PROJECT', 'Special Project')], max_length=20),
        ),
        migrations.AlterField(
            model_name='generateddocumentnumber',
            name='document_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('QUOTATION', 'Quotation'), ('WCR', 'Work Completion Report'), ('BOQ', 'BOQ'), ('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase Order'), ('SCHEDULE', 'Work Schedule'), ('ENQUIRY', 'Enquiry'), ('ESTIMATE_BOQ', 'Estimate BOQ'), ('REQUEST', 'Employee Request'), ('SPECIAL_PROJECT', 'Special Project')], max_length=20),
        ),
    ]
