# Generated by Django 6.1.1 on 2026-09-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0006_special_projects_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentnumbersettings',
            name='pm_prefix',
            field=models.CharField(default='PM', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentcounter',
            name='document_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('QUOTATION', 'Quotation'), ('WCR', 'Work Completion Report'), ('BOQ', 'BOQ'), ('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase Order'), ('SCHEDULE', 'Work Schedule'), ('ENQUIRY', 'Enquiry'), ('ESTIMATE_BOQ', 'Estimate BOQ'), ('REQUEST', 'Employee Request'), ('SPECIAL_PROJECT', 'Special Project'), ('PM_OBSERVATION', 'PM Observation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='generateddocumentnumber',
            name='document_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('QUOTATION', 'Quotation'), ('WCR', 'Work Completion Report'), ('BOQ', 'BOQ'), ('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase Order'), ('SCHEDULE', 'Work Schedule'), ('ENQUIRY', 'Enquiry'), ('ESTIMATE_BOQ', 'Estimate BOQ'), ('REQUEST', 'Employee Request'), ('SPECIAL_PROJECT', 'Special Project'), ('PM_OBSERVATION', 'PM Observation')], max_length=20),
        ),
    ]
