# Generated by Django 6.0.3 on 2026-06-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcompletionreport',
            name='wcr_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
