# Generated by Django 6.0.3 on 2026-06-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcr', '0002_workcompletionreport_wcr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcompletionreport',
            name='authorized_signatory_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workcompletionreport',
            name='authorized_signatory_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workcompletionreport',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
