# Generated by Django 6.0.3 on 2026-06-13 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_workschedule_expected_duration_hours_and_more'),
        ('wcr', '0003_workcompletionreport_authorized_signatory_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcompletionreport',
            name='completion_status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PARTIAL', 'Partially Completed'), ('PENDING', 'Pending')], default='COMPLETED', max_length=15),
        ),
        migrations.AddField(
            model_name='workcompletionreport',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcrs', to='scheduling.workschedule'),
        ),
        migrations.AddField(
            model_name='workcompletionreport',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='workcompletionreport',
            name='work_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workcompletionreport',
            name='work_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
