# Generated by Django 6.0.3 on 2026-06-13 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
        ('orders', '0003_order_expected_completion_date_order_order_date_and_more'),
        ('wcr', '0004_workcompletionreport_completion_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcompletionreport',
            name='enquiry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_wcr', to='enquiries.enquiry'),
        ),
        migrations.AddField(
            model_name='workcompletionreport',
            name='feasibility_remarks',
            field=models.TextField(blank=True, verbose_name='Feasibility Remarks'),
        ),
        migrations.AddField(
            model_name='workcompletionreport',
            name='site_findings',
            field=models.TextField(blank=True, verbose_name='Site Findings'),
        ),
        migrations.AddField(
            model_name='workcompletionreport',
            name='wcr_type',
            field=models.CharField(choices=[('EXECUTION', 'Execution WCR'), ('SURVEY', 'Survey WCR')], default='EXECUTION', max_length=12),
        ),
        migrations.AlterField(
            model_name='workcompletionreport',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
