# Generated by Django 6.0.3 on 2026-03-04 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_address', models.TextField()),
                ('order_type', models.CharField(choices=[('SURVEY', 'Survey'), ('INSTALLATION', 'Installation'), ('COMPLAINT', 'Complaint'), ('MAINTENANCE', 'Maintenance')], max_length=20)),
                ('description', models.TextField()),
                ('priority', models.CharField(default='Normal', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('WCR_SUBMITTED', 'WCR Submitted'), ('APPROVED', 'Approved'), ('BILLED', 'Billed'), ('PAYMENT_PENDING', 'Payment Pending'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
