# Generated by Django 6.0.3 on 2026-06-04 15:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0002_order_order_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=30, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(default='Nos', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_revision_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_rates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('quotation_date', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField()),
                ('contact_person', models.CharField(max_length=100)),
                ('site_location', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('scope_of_work', models.TextField()),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted To Order')], default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_approved', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='clients.client')),
                ('converted_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_source', to='orders.order')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quotation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationMaterialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='Nos', max_length=20)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('line_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('material_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_lines', to='quotations.materialratecard')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_lines', to='quotations.quotation')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RateCardAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('SERVICE', 'Service Rate Card'), ('MATERIAL', 'Material Rate Card')], max_length=10)),
                ('record_code', models.CharField(max_length=30)),
                ('record_name', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], max_length=10)),
                ('field_name', models.CharField(blank=True, max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('revised_at', models.DateTimeField(auto_now_add=True)),
                ('revised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_card_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-revised_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=30, unique=True)),
                ('service_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='Nos', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_revision_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_rates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['service_code'],
            },
        ),
        migrations.CreateModel(
            name='QuotationServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='Nos', max_length=20)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('line_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='quotations.quotation')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_lines', to='quotations.serviceratecard')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
