# Generated by Django 6.0.3 on 2026-06-06 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.TextField(default='1. Billing shall be based on actual quantities executed and supplied.\n\n2. Purchase Order (PO) must be issued in favour of:\n   Infomates Techno Solutions (P) Ltd\n   Bava Complex, Thammanam, Kochi – 682032.\n\n3. Implementation period: Within 30 working days from receipt of Purchase Order, advance payment (if applicable), and site readiness.\n\n4. Taxes:\n   GST and other applicable taxes shall be charged as per prevailing Government regulations at the time of invoicing. Any statutory changes after submission of the quotation shall be charged extra.\n\n5. All required permissions, approvals, landlord consent, and statutory clearances shall be arranged by the customer before commencement of work.\n\n6. Mode of Payment:\n   All payments shall be made through Cheque, Demand Draft (DD), RTGS, NEFT, or Bank Transfer favouring:\n   Infomates Techno Solutions (P) Ltd\n\n9. Prices and material availability are subject to market fluctuations and stock availability. Therefore, final pricing and delivery schedules may vary slightly at the time of order confirmation.\n\n10. Any additional work, materials, services, civil work, electrical work, transportation, permissions, or requirements not specifically mentioned in this quotation shall be charged extra.', help_text='Standard terms printed on every quotation.')),
                ('payment_terms', models.TextField(default='Payment Terms:\n\n* Payment for supply materials shall be made in advance against Purchase Order (PO) or written order confirmation.\n* Balance payment shall be released within 10 days from completion of work and submission of invoice.', help_text='Payment terms section.')),
                ('validity_period', models.TextField(default='Quotation Validity:\nThis quotation is valid for one (1) week from the date of quotation.', help_text='Validity wording shown on quotations.')),
                ('validity_days', models.PositiveSmallIntegerField(default=7, help_text='Default number of days for Valid Until on new quotations.')),
                ('bank_details', models.TextField(default='Bank Name: Union Bank of India\nBranch: Ponnurunni\nAccount No: 423701010037146\nIFSC: UBIN0542377\nAccount Name: Infomates Techno Solutions (P) Ltd', help_text='Company bank details printed on quotations.')),
                ('footer_notes', models.TextField(blank=True, default='', help_text='Optional footer notes below the signature block.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quotation settings',
                'verbose_name_plural': 'Quotation settings',
            },
        ),
    ]
