# Generated by Django 6.0.3 on 2026-06-06 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotation_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='covering_letter_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='covering_letter_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='include_company_seal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='include_covering_letter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='include_signature',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='include_terms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='reference_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='CoveringLetterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_introduction', models.TextField(default='Infomates Techno Solutions (P) Ltd is a leading provider of telecom, IT, networking, and field service solutions.')),
                ('default_subject', models.CharField(default='Submission of Commercial Proposal / Quotation', max_length=255)),
                ('default_body', models.TextField(default='Dear Sir/Madam,\n\nGreetings from Infomates Techno Solutions (P) Ltd.\n\nWe thank you for the opportunity to submit our proposal for the subject work.\n\nBased on the discussions, site survey, and requirements shared, we are pleased to submit our commercial proposal for your kind consideration.\n\nWe assure you of our best services and support and look forward to establishing a long-term business relationship with your esteemed organization.\n\nThe detailed quotation is enclosed for your review.\n\nShould you require any clarification, please feel free to contact us.\n\nThanking you and assuring you of our best attention at all times.\n\nYours faithfully,\n\nFor Infomates Techno Solutions (P) Ltd\n\nAuthorized Signatory')),
                ('closing_paragraph', models.TextField(default='Thanking you and assuring you of our best attention at all times.')),
                ('signatory_name', models.CharField(default='V N Manoj', max_length=100)),
                ('designation', models.CharField(default='Authorized Signatory', max_length=100)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='quotations/signatures/')),
                ('company_seal', models.ImageField(blank=True, null=True, upload_to='quotations/seals/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covering_letter_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Covering letter settings',
                'verbose_name_plural': 'Covering letter settings',
            },
        ),
        migrations.CreateModel(
            name='ProposalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='proposal_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='quotations.proposaltemplate'),
        ),
    ]
