# Generated by Django 6.0.3 on 2026-06-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_migrate_signatory_to_company_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveringlettersettings',
            name='company_seal',
        ),
        migrations.RemoveField(
            model_name='coveringlettersettings',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='coveringlettersettings',
            name='signatory_name',
        ),
        migrations.RemoveField(
            model_name='coveringlettersettings',
            name='signature_image',
        ),
    ]
