# Generated by Django 6.0.3 on 2026-06-12 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
        ('estimate_boq', '0001_initial'),
        ('quotations', '0006_quotation_authorized_signatory_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='enquiries.enquiry'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='estimate_boq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='estimate_boq.estimateboq'),
        ),
    ]
