# Generated by Django 6.0.3 on 2026-07-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_quotation_enquiry_quotation_estimate_boq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveringlettersettings',
            name='default_body',
            field=models.TextField(default='Dear Sir/Madam,\n\nGreetings from Infomates Techno Solutions (P) Ltd.\n\nWe thank you for the opportunity to submit our proposal for the subject work.\n\nBased on the discussions, site survey, and requirements shared, we are pleased to submit our commercial proposal for your kind consideration.\n\nWe assure you of our best services and support and look forward to establishing a long-term business relationship with your esteemed organization.\n\nThe detailed quotation is enclosed for your review.\n\nShould you require any clarification, please feel free to contact us.\n\nThanking you and assuring you of our best attention at all times.'),
        ),
    ]
