# Generated by Django 6.0.3 on 2026-07-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_enhancement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendance__employe_27e0c1_idx',
            old_name='attendance_employe_6a8f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendance__attenda_f3ac94_idx',
            old_name='attendance_attenda_8b2c1a_idx',
        ),
    ]
